### ISSUE TITLE
Support for 1 Day / 1 Week Performance

### ISSUE THREAD

**Issue by NovaCyntax** [investbrainapp/investbrain#23]
Support for visualizing short-term changes in portfolio performance

![Screenshot_20241109-200049](https://github.com/user-attachments/assets/f223337a-f2fb-4de0-ae26-f9654ee0413f)

Above are some example timelines present in Delta, which is one of the more popular portfolio tracking applications.

**Comment by hackerESQ** [comment]
Great idea! This would require capturing market changes more frequently. And would also affect the sync daily changes command.

I'll add this to the list of roadmap items!
