### ISSUE TITLE
Unable to Edit Transactions from Transactions Screen

### ISSUE THREAD

**Issue by Phaeton** [investbrainapp/investbrain#24]
I have an older transaction that I am trying to edit. I am only able to update transactions from the holdings screen, but that screen only shows the 10 most recent transactions. I was attempting to load older transactions and keyed in a cost basis incorrectly. I see no way to delete or edit the older transaction.

Is there the ability or plan to import transactions via .csv or other methods?

**Comment by hackerESQ** [comment]
Yikes, yeah, currently only showing the last 10 transactions on the recent activity card. I'll have to add pagination to this.

Thanks for the heads up!

**Comment by hackerESQ** [comment]
This was added in the latest release (v1.0.5)!
