### ISSUE TITLE
Bug: Issue with Dividends?

### ISSUE THREAD

**Issue by tynorton** [investbrainapp/investbrain#26]
**Problem**
Seeing a very large sum that doesn't make sense in dividend view for AMAT symbol.

![image](https://github.com/user-attachments/assets/cd733684-c051-4055-a920-44ab533223c2)

**Expected**
Dividend values should make sense

**Comment by tynorton** [comment]
Refreshed this morning without any data changes and the shares used by the first dividend jumped up even more.
![image](https://github.com/user-attachments/assets/4414ed70-3188-49f6-ac90-057d44ad8b59)

**Comment by hackerESQ** [comment]
That's wild. Can you share an export of that portfolio so I can take a look?

**Comment by hackerESQ** [comment]
Disregard the request for an export. Looks like you are using the hosted version as well. Seeing multiple rows in the `dividends` table for AMAT. Specifically for Aug 22. Investigating.

**Comment by hackerESQ** [comment]
Hi @tynorton, I've identified the issue and it should be resolved by the referenced commit above. I am tagging a new release now. Hoping you can confirm this resolves the issue?

Even once you update, you may still have erroneous dividends. To clear the previous / erroneous dividends, you can use the following query which is what I just ran for the hosted version:

```sql
WITH RankedDividends AS (
    SELECT 
        id,
        symbol,
        date,
        dividend_amount,
        ROW_NUMBER() OVER (PARTITION BY symbol, date ORDER BY id) AS row_num
    FROM dividends
)
DELETE FROM dividends
WHERE id IN (
    SELECT id
    FROM RankedDividends
    WHERE row_num > 1
);

```
