### ISSUE TITLE
support for index funds

### ISSUE THREAD

**Issue by aetaric** [investbrainapp/investbrain#41]
I have a 401k I'm trying to track with investbrain. The 401k is primarily using an index fund which fails on trying to update the portfolio data with the following:
```
 % sudo docker exec -it investbrain-app php artisan sync:daily-change    

 ┌ Choose the portfolio you wish to re-calculate: ──────────────┐
 │ Work 401k                                                    │
 └──────────────────────────────────────────────────────────────┘

Syncing daily change history... This may take a moment.
Could not get market data: Not a number in column "open": open
```

It would be nice if index funds worked correctly so I can see a more accurate picture of my investments.

**Comment by hackerESQ** [comment]
I've had no issues with many index functions from my 401k. 

What is the index fund that's causing problems?  Also, what market data provider are you using? 

Ultimately, this is a problem that can be solved by a market data provider. Especially with the graceful fallback mechanism, you could add a custom market data provider to handle these exceptions.

**Comment by aetaric** [comment]
Fund symbol having issues is WBRPOX. Currently using only yahoo, but I guess I can setup others if need be.

**Comment by hackerESQ** [comment]
I'll have to do some investigation. Looks like symbol _is_ available on Yahoo finance:

![image](https://github.com/user-attachments/assets/a6f85268-df6b-4cf5-8a6c-6eba76130f24)

**Comment by hackerESQ** [comment]
Hi @aetaric, I've narrowed down the root cause to the library we use for Yahoo market data.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/d63a51dc-d6b2-49ab-b064-113a1a549771" />

I'll throw together a patch and get this sorted shortly.

**Comment by hackerESQ** [comment]
Submitted a PR (scheb/yahoo-finance-api#58). Will keep this open until that's resolved.

**Comment by hackerESQ** [comment]
This should be resolved now!
