### ISSUE TITLE
Add import transactions from interactivebrokers

### ISSUE THREAD

**Issue by cema93** [investbrainapp/investbrain#42]
PLS Add import transactions from interactivebrokers via csv file

**Comment by hackerESQ** [comment]
Hi @cema93, there are currently no plans to add imports for brokers. That would be essentially unlimited scope and the incremental value for the community is limited.

In time, I've considered adding a browser extension to "watch" for new transactions and capture them in Investbrain. This would likely have more meaningful impact to the community. 

My recommendation is to look at the [Import/Export section](https://github.com/investbrainapp/investbrain?tab=readme-ov-file#import--export) of the readme and wrangle your current csv into the expected Investbrain format. Very likely you only have to shift a few columns around.
