### ISSUE TITLE
issue with calculating the S&P500 index ( yahoo marker ^GSPC

### ISSUE THREAD

**Issue by hagai-biton2** [investbrainapp/investbrain#45]
as you can see from the image there is an issue with calculating the S&P500 index ( yahoo marker ^GSPC)
it shows  the entire worth of the index as my Total Market Value and Market Gain/Loss 
now I would love to have $6,398,443.78 but then I would pay someone to do this tracking for me....

![image](https://github.com/user-attachments/assets/49f75ac2-226b-4a1e-9be2-0d470b9c6fe7)

**Comment by hackerESQ** [comment]
Which market data provider are you using?

**Comment by hagai-biton2** [comment]
yahoo

**Comment by hackerESQ** [comment]
I'm not able to reproduce this. 

<img width="755" alt="image" src="https://github.com/user-attachments/assets/9f3ad389-829d-4a04-ac2b-74e675686fcf" />


Can you share an export of the portfolio with this holding?

**Comment by hagai-biton2** [comment]
[2024_12_19_investbrain_backup_only_s&p.xlsx](https://github.com/user-attachments/files/18260038/2024_12_19_investbrain_backup_only_s.p.xlsx)
![image](https://github.com/user-attachments/assets/a1122883-79ef-49c9-aa83-4e6956ddbbcf)

this is with the docker image from last night (26.12.2024) did the git clone and then docker up , I ran the syc: + capture cli commends.

**Comment by hagai-biton2** [comment]
this can be closed and marked solved, it was my misunderstanding of how to convert the fund numbers I had to actual ^GSPC rate and data.
