### ISSUE TITLE
arm64 vs amd64

### ISSUE THREAD

**Issue by gonsalvesc** [investbrainapp/investbrain#46]
Trying to run the app on a Ubuntu VM. Got the below message when I try to bring up the container.

`! app The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v2) and no specific platform was requested`

**Comment by hackerESQ** [comment]
Looks like I haven't been building the image with multi-platform in mind. Just pushed some new images to dockerhub. Can you give it another shot?

**Comment by hackerESQ** [comment]
This seems fixed so I'm closing for now. We can re-open if this is still an issue.

**Comment by gonsalvesc** [comment]
It's fixed! Thank you!
