### ISSUE TITLE
Docker image doesn't start in Kubernetes

### ISSUE THREAD

**Issue by Marx2** [investbrainapp/investbrain#47]
Latest changes made image to start, but start takes a long time, and finishes with lines:
```
vite v5.4.10 building for production...
transforming...

🌼   daisyUI 4.12.10
├─ ✔︎ 2 themes added		https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:	https://opencollective.com/daisyui
2024-12-20T22:20:56.282771035+01:00
```

There are also a few other missing pieces:
- probes are not defined (startup, readiness etc)
- it was supposed for Redis to be separated, but no description exists what variables to set
- image in dockerhub should be tagged according to semantic versioning (using "latest" is discouraged)

**Comment by hackerESQ** [comment]
That's good progress. Glad that helped. 

Just tagged a v1.0.8 image on dockerhub. Looking into github actions to keep the image in sync with the github repo.

Redis can be configured using these configs in the .env (check out the [.env.example](https://github.com/investbrainapp/investbrain/blob/main/.env.example)):
- REDIS_HOST=investbrain-redis
- REDIS_PATH=/tmp/database_server.sock
- REDIS_PASSWORD=null
- REDIS_PORT=6379

No idea what you mean by probes. I'm willing to review and merge any PRs if you have suggestions there.

As I mentioned in response to your note in #27, support for K8s will need to be a contributed by the community.  As such, I'm closing this issue.

**Comment by rafaribe** [comment]
Hey @hackerESQ, maybe you can also push to ghcr here on github? Would avoid the dockerhub limiting issues.

**Comment by Marx2** [comment]
new container behaves still doesn't start fully, it ends up on lines:
```
  90/149 [================>-----------]  60%
 110/149 [====================>-------]  73%
 125/149 [=======================>----]  83%
 136/149 [=========================>--]  91%
 149/149 [============================] 100%
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
```

**Comment by hackerESQ** [comment]
So `entrypoint.sh` is running. You're getting stuck at [Line 35](https://github.com/investbrainapp/investbrain/blob/643bbe3af27918f1f6956fe6d3cb88add5c165cc/docker/entrypoint.sh#L35).

I suspect there may be something wrong with your DB setup? Have you configured the DB_HOST, etc. environment variables?

The next expected log message should be "Running migrations..." Do you see that message?

**Comment by Marx2** [comment]
DB_HOST is also not documented. I've added it but problem is still the same.
I've set such variables:

APP_PORT : 443
APP_TIMEZONE : Europe/Warsaw
APP_URL : investbrain.something.com
DB_HOST : mariadb-galera.database
MYSQL_DATABASE : ib
MYSQL_PASSWORD : **********
MYSQL_ROOT_PASSWORD : **********
MYSQL_USER : ib
REDIS_HOST : ib-redis.pfire.svc.cluster.local
REGISTRATION_ENABLED : false

**Comment by rafaribe** [comment]
Yeah I also tried this image with Postgres but was unable to have it running

**Comment by Marx2** [comment]
As I know Postgres is not supported.

v1.0.9 - still the same problem, no successful startup, no clear message what happens. Giving more logs (like: "connecting to Redis", "connecting to MySql") could greatly help in debugging.

Docker image is build in a wrong way. Image should already contain pre-built binaries. Currently it builds during startup which is wrong approach. During startup no build should happen, only start.

As for probes:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
It's kubernetes thing, but doesn't harm any other environments, and can also be leveraged there (for example to monitor liveness of service)

**Comment by rafaribe** [comment]
> As I know Postgres is not supported.
> 
> v1.0.9 - still the same problem, no successful startup, no clear message what happens. Giving more logs (like: "connecting to Redis", "connecting to MySql") could greatly help in debugging.
> 
> Docker image is build in a wrong way. Image should already contain pre-built binaries. Currently it builds during startup which is wrong approach. During startup no build should happen, only start.
> 
> As for probes: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ It's kubernetes thing, but doesn't harm any other environments, and can also be leveraged there (for example to monitor liveness of service)

It should be though, according to the code and `DB_CONNECTION` variable.

Agree with all the points above. Docker image should be standalone for client / server or you split into 2 images

**Comment by Marx2** [comment]
The author closed this task despite not being resolved. Not nice :(

**Comment by hackeresq** [comment]
> The author closed this task despite not being resolved. Not nice :(

I've made it clear that K8s support will have to be contributed by the community. Time spent fussing with K8s takes away from features on the roadmap.  

I am more than happy to merge pull requests or discuss if you'd like to contribute. In which case, there's a discussion waiting... #27
